Project vapor_auth_be {
    database_type: "postgres"
}

Enum Authority {
    ROLE_CREATE
    ROLE_UPDATE
    ROLE_DELETE
    GROUP_UPDATE
    GROUP_DELETE
}

Table role {
    id int [increment]
    name string
    group_uuid string
    authority Authority

    Indexes {
        (name, group_uuid, id) [pk]
    }
}

Table user {
    uuid string [pk, note: "from the idp"]
    created_at timestamp
}

Table user_group {
    user_uuid string [ref: > user.uuid]
    group_uuid string [ref: > group.uuid]
    created_at timestamp

    Indexes {
        (user_uuid, group_uuid) [pk]
    }
}

Table user_role {
    user_uuid string [ref: > user.uuid]
    group_uuid string [ref: > group.uuid]
    role_id int [ref: > role.id]

    Indexes {
        (user_uuid, group_uuid) [pk]
    }
}

Table group {
    uuid string [pk]
    name string [unique]
    description string
    created_at timestamp
}