name: update erd

on:
  push:
    paths:
      - 'prisma/**'
    branches:
      - master

jobs:
  build:
    name: Generate and Build ERD
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install prisma-dbml-generator
        run: sudo npm install -g prisma-dbml-generator

      - name: Generate dbml
        run: prisma generate

      - name: Install dbdocs
        run: sudo npm install -g dbdocs

      - name: Check dbdocs
        run: dbdocs --version

      - name: Build and Update ERD
        run: dbdocs build ./prisma/dbml/schema.dbml
        env:
          DBDOCS_TOKEN: ${{ secrets.DBDOCS_TOKEN }}
